#!/bin/bash
#SBATCH --job-name=perturbR_usecase
#SBATCH --array=1-5
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --output=UseCase/msi/logs/perturbR_%A_%a.out
#SBATCH --error=UseCase/msi/logs/perturbR_%A_%a.err
#SBATCH --mail-user=ong00042@umn.edu
#SBATCH --mail-type=BEGIN,END,FAIL

module load R

Rscript UseCase/msi/run_one_param.R ${SLURM_ARRAY_TASK_ID}