#!/bin/bash
#SBATCH --job-name=perturbR_usecase
#SBATCH --array=1-5
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --output=UseCase/msi/logs/perturbR_%A_%a.out
#SBATCH --error=UseCase/msi/logs/perturbR_%A_%a.err
#SBATCH --mail-user=ong00042@umn.edu
#SBATCH --mail-type=BEGIN,END,FAIL

module purge
module load R/4.2.2-gcc-8.2.0-vp7tyde

which R
R --version
which Rscript


Rscript UseCase/msi/run_one_param.R ${SLURM_ARRAY_TASK_ID}